#!/usr/bin/bash

#----------------------------------------------------------------------------------------------------------------------#
# Sets the USER's API key in the configuration file.                                                                   #
#----------------------------------------------------------------------------------------------------------------------#

if [ "$(pip show pyTNG)" = "" ]; then
  echo -e "[\x1b[36;49mpytng\x1b[39;49m] - [\x1b[36;49mapikey\x1b[39;49m]: [\x1b[31mERROR\x1b[39;49m] pip indicates no pyTNG installation."
  exit 1
fi

INSTALL=$(pip show pyTNG | grep 'Location:' | sed 's|Location: ||')
CONFIG="$INSTALL/pyTNG/bin/config.yaml"
echo -e "[\x1b[36;49mpytng\x1b[39;49m] - [\x1b[36;49mapikey\x1b[39;49m]: pyTNG installation detected at $INSTALL."
echo -e "[\x1b[36;49mpytng\x1b[39;49m] - [\x1b[36;49mapikey\x1b[39;49m]: Expecting to find config.yaml at $CONFIG."

if [ -f "$CONFIG" ]; then
  echo -e "[\x1b[36;49mpytng\x1b[39;49m] - [\x1b[36;49mapikey\x1b[39;49m]: FOUND config.yaml at $CONFIG. Proceeding."
else
  echo -e "[\x1b[36;49mpytng\x1b[39;49m] - [\x1b[36;49mapikey\x1b[39;49m]: [\x1b[31mERROR\x1b[39;49m] config.yaml at $CONFIG wasn't found."
  exit 1
fi

USER_API_KEY="$1"

echo -e "[\x1b[36;49mpytng\x1b[39;49m] - [\x1b[36;49mapikey\x1b[39;49m]: Config path: $CONFIG"
echo -e "[\x1b[36;49mpytng\x1b[39;49m] - [\x1b[36;49mapikey\x1b[39;49m]: Setting APIKEY for TNG API access to \x1b[31m$USER_API_KEY\x1b[39m."


sed -i -E "s|(  api_key: )\"([^\"]*)\"(.*)|\1\"$USER_API_KEY\"\3|g" $CONFIG

echo -e "[\x1b[36;49mpytng\x1b[39;49m] - [\x1b[36;49mapikey\x1b[39;49m]: \x1b[32;49mAPIKEY successfully set to \x1b[36;49m$USER_API_KEY\x1b[39;49m."
